apiVersion: batch/v1
kind: Job
metadata:
  name: run-tests-job-${PELTON_RUN}
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        test-job: relaxation-${PELTON_RUN}
    spec:
      restartPolicy: Never
      containers:
      - name: run-tests-ctnr-${PELTON_RUN}
        image: ${PELTON_BUILD_RESULT}
